"""adicionado table posts

Revision ID: aa7a4d8b483a
Revises: a949d64995d2
Create Date: 2024-12-28 19:49:59.354115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7a4d8b483a'
down_revision = 'a949d64995d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Posts_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_Posts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_Posts_timestamp'))

    op.drop_table('Posts')
    # ### end Alembic commands ###
